# Bu dosya, projenizin ana dizininde olmalıdır.
# Netlify'a projenizi nasıl oluşturacağını ve fonksiyonları nerede bulacağını söyler.

[build]
  # Projeyi yayına hazırlamak için çalıştırılacak komut
  command = "npm run build"
  
  # Yayına alınacak dosyaların bulunduğu klasör (Vite için 'dist')
  publish = "dist"
  
  # Arka plan kodlarımızın (fonksiyonlarımızın) bulunduğu klasör
  functions = "netlify/functions"

[functions]
  # Arka plan kodumuzun çalışması için gerekli olan Node.js sürümünü belirtir.
  node_bundler = "esbuild"
  node_version = 18
